export const mainColorBlue = '#60D3E0'
export const mainColorBlack = '#333333'
export const mainColorYellow = '#FFC545'
export const subColorLightGrey = '#dddddd'
export const descriptionColor = '#cccccc'
export const darkGrey = '#b3b3b3'
